name: Run Python tests

on:
  push:
    branches:
      - main

  workflow_dispatch:  # run manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Prepare environment
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov=src --cov-report=term-missing --cov-report=json:.coverage.json

      - name: Check if coverage is >= 90%
        run: |
          set -e

          json=$(< .coverage.json)
          coverage=$(
            echo $json \
            | grep -oE '"totals": \{[^}]*"percent_covered": ?[0-9]+' \
            | grep -oE "[0-9]+$"
          )

          if [[ $coverage -lt 90 ]]; then
            echo "Did not meet coverage threshold (got $coverage%, expected at least 90%)"
            exit 1
          fi
